[tool.poetry]
name = "api"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pytest = "^8.1.1"
black = "^24.3.0"
flake8 = "^7.0.0"
pandas = "^2.2.2"
geopandas = "^0.14.3"
matplotlib = "^3.8.4"
gtfs-functions = "^2.5"
gtfs-kit = "^6.1.0"
keplergl = "^0.3.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
